receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "ecs-metrics"
          static_configs:
            - targets: ["localhost:8000"]

exporters:
  awsprometheusremotewrite:
    endpoint: "${AMP_ENDPOINT}"
    aws_auth:
      region: "${AWS_REGION}"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [awsprometheusremotewrite]

